<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $district = array(
            array('district_title' => 'Anantnag','state_id' => '15'),
            array('district_title' => 'Bandipore','state_id' => '15'),
            array('district_title' => 'Baramulla','state_id' => '15'),
            array('district_title' => 'Budgam','state_id' => '15'),
            array('district_title' => 'Doda','state_id' => '15'),
            array('district_title' => 'Ganderbal','state_id' => '15'),
            array('district_title' => 'Jammu','state_id' => '15'),
            array('district_title' => 'Kargil','state_id' => '15'),
            array('district_title' => 'Kathua','state_id' => '15'),
            array('district_title' => 'Kishtwar','state_id' => '15'),
            array('district_title' => 'Kulgam','state_id' => '15'),
            array('district_title' => 'Kupwara','state_id' => '15'),
            array('district_title' => 'Leh (Ladakh)','state_id' => '15'),
            array('district_title' => 'Poonch','state_id' => '15'),
            array('district_title' => 'Pulwama','state_id' => '15'),
            array('district_title' => 'Rajouri','state_id' => '15'),
            array('district_title' => 'Ramban','state_id' => '15'),
            array('district_title' => 'Reasi','state_id' => '15'),
            array('district_title' => 'Samba','state_id' => '15'),
            array('district_title' => 'Shopian','state_id' => '15'),
            array('district_title' => 'Srinagar','state_id' => '15'),
            array('district_title' => 'Udhampur','state_id' => '15'),
            array('district_title' => 'Bilaspur (Himachal Pradesh)','state_id' => '14'),
            array('district_title' => 'Chamba','state_id' => '14'),
            array('district_title' => 'Hamirpur (Himachal Pradesh)','state_id' => '14'),
            array('district_title' => 'Kangra','state_id' => '14'),
            array('district_title' => 'Kinnaur','state_id' => '14'),
            array('district_title' => 'Kullu','state_id' => '14'),
            array('district_title' => 'Lahul & Spiti','state_id' => '14'),
            array('district_title' => 'Mandi','state_id' => '14'),
            array('district_title' => 'Shimla','state_id' => '14'),
            array('district_title' => 'Sirmaur','state_id' => '14'),
            array('district_title' => 'Solan','state_id' => '14'),
            array('district_title' => 'Una','state_id' => '14'),
            array('district_title' => 'Amritsar','state_id' => '28'),
            array('district_title' => 'Barnala','state_id' => '28'),
            array('district_title' => 'Bathinda','state_id' => '28'),
            array('district_title' => 'Faridkot','state_id' => '28'),
            array('district_title' => 'Fatehgarh Sahib','state_id' => '28'),
            array('district_title' => 'Firozpur','state_id' => '28'),
            array('district_title' => 'Gurdaspur','state_id' => '28'),
            array('district_title' => 'Hoshiarpur','state_id' => '28'),
            array('district_title' => 'Jalandhar','state_id' => '28'),
            array('district_title' => 'Kapurthala','state_id' => '28'),
            array('district_title' => 'Ludhiana','state_id' => '28'),
            array('district_title' => 'Mansa','state_id' => '28'),
            array('district_title' => 'Moga','state_id' => '28'),
            array('district_title' => 'Muktsar','state_id' => '28'),
            array('district_title' => 'Patiala','state_id' => '28'),
            array('district_title' => 'Rupnagar (Ropar)','state_id' => '28'),
            array('district_title' => 'Sahibzada Ajit Singh Nagar (Mohali)','state_id' => '28'),
            array('district_title' => 'Sangrur','state_id' => '28'),
            array('district_title' => 'Shahid Bhagat Singh Nagar (Nawanshahr)','state_id' => '28'),
            array('district_title' => 'Tarn Taran','state_id' => '28'),
            array('district_title' => 'Chandigarh','state_id' => '6'),
            array('district_title' => 'Almora','state_id' => '34'),
            array('district_title' => 'Bageshwar','state_id' => '34'),
            array('district_title' => 'Chamoli','state_id' => '34'),
            array('district_title' => 'Champawat','state_id' => '34'),
            array('district_title' => 'Dehradun','state_id' => '34'),
            array('district_title' => 'Haridwar','state_id' => '34'),
            array('district_title' => 'Nainital','state_id' => '34'),
            array('district_title' => 'Pauri Garhwal','state_id' => '34'),
            array('district_title' => 'Pithoragarh','state_id' => '34'),
            array('district_title' => 'Rudraprayag','state_id' => '34'),
            array('district_title' => 'Tehri Garhwal','state_id' => '34'),
            array('district_title' => 'Udham Singh Nagar','state_id' => '34'),
            array('district_title' => 'Uttarkashi','state_id' => '34'),
            array('district_title' => 'Ambala','state_id' => '13'),
            array('district_title' => 'Bhiwani','state_id' => '13'),
            array('district_title' => 'Faridabad','state_id' => '13'),
            array('district_title' => 'Fatehabad','state_id' => '13'),
            array('district_title' => 'Gurgaon','state_id' => '13'),
            array('district_title' => 'Hisar','state_id' => '13'),
            array('district_title' => 'Jhajjar','state_id' => '13'),
            array('district_title' => 'Jind','state_id' => '13'),
            array('district_title' => 'Kaithal','state_id' => '13'),
            array('district_title' => 'Karnal','state_id' => '13'),
            array('district_title' => 'Kurukshetra','state_id' => '13'),
            array('district_title' => 'Mahendragarh','state_id' => '13'),
            array('district_title' => 'Mewat','state_id' => '13'),
            array('district_title' => 'Palwal','state_id' => '13'),
            array('district_title' => 'Panchkula','state_id' => '13'),
            array('district_title' => 'Panipat','state_id' => '13'),
            array('district_title' => 'Rewari','state_id' => '13'),
            array('district_title' => 'Rohtak','state_id' => '13'),
            array('district_title' => 'Sirsa','state_id' => '13'),
            array('district_title' => 'Sonipat','state_id' => '13'),
            array('district_title' => 'Yamuna Nagar','state_id' => '13'),
            array('district_title' => 'Central Delhi','state_id' => '10'),
            array('district_title' => 'East Delhi','state_id' => '10'),
            array('district_title' => 'New Delhi','state_id' => '10'),
            array('district_title' => 'North Delhi','state_id' => '10'),
            array('district_title' => 'North East Delhi','state_id' => '10'),
            array('district_title' => 'North West Delhi','state_id' => '10'),
            array('district_title' => 'South Delhi','state_id' => '10'),
            array('district_title' => 'South West Delhi','state_id' => '10'),
            array('district_title' => 'West Delhi','state_id' => '10'),
            array('district_title' => 'Ajmer','state_id' => '29'),
            array('district_title' => 'Alwar','state_id' => '29'),
            array('district_title' => 'Banswara','state_id' => '29'),
            array('district_title' => 'Baran','state_id' => '29'),
            array('district_title' => 'Barmer','state_id' => '29'),
            array('district_title' => 'Bharatpur','state_id' => '29'),
            array('district_title' => 'Bhilwara','state_id' => '29'),
            array('district_title' => 'Bikaner','state_id' => '29'),
            array('district_title' => 'Bundi','state_id' => '29'),
            array('district_title' => 'Chittorgarh','state_id' => '29'),
            array('district_title' => 'Churu','state_id' => '29'),
            array('district_title' => 'Dausa','state_id' => '29'),
            array('district_title' => 'Dholpur','state_id' => '29'),
            array('district_title' => 'Dungarpur','state_id' => '29'),
            array('district_title' => 'Ganganagar','state_id' => '29'),
            array('district_title' => 'Hanumangarh','state_id' => '29'),
            array('district_title' => 'Jaipur','state_id' => '29'),
            array('district_title' => 'Jaisalmer','state_id' => '29'),
            array('district_title' => 'Jalor','state_id' => '29'),
            array('district_title' => 'Jhalawar','state_id' => '29'),
            array('district_title' => 'Jhunjhunu','state_id' => '29'),
            array('district_title' => 'Jodhpur','state_id' => '29'),
            array('district_title' => 'Karauli','state_id' => '29'),
            array('district_title' => 'Kota','state_id' => '29'),
            array('district_title' => 'Nagaur','state_id' => '29'),
            array('district_title' => 'Pali','state_id' => '29'),
            array('district_title' => 'Pratapgarh (Rajasthan)','state_id' => '29'),
            array('district_title' => 'Rajsamand','state_id' => '29'),
            array('district_title' => 'Sawai Madhopur','state_id' => '29'),
            array('district_title' => 'Sikar','state_id' => '29'),
            array('district_title' => 'Sirohi','state_id' => '29'),
            array('district_title' => 'Tonk','state_id' => '29'),
            array('district_title' => 'Udaipur','state_id' => '29'),
            array('district_title' => 'Agra','state_id' => '33'),
            array('district_title' => 'Aligarh','state_id' => '33'),
            array('district_title' => 'Allahabad','state_id' => '33'),
            array('district_title' => 'Ambedkar Nagar','state_id' => '33'),
            array('district_title' => 'Auraiya','state_id' => '33'),
            array('district_title' => 'Azamgarh','state_id' => '33'),
            array('district_title' => 'Bagpat','state_id' => '33'),
            array('district_title' => 'Bahraich','state_id' => '33'),
            array('district_title' => 'Ballia','state_id' => '33'),
            array('district_title' => 'Balrampur','state_id' => '33'),
            array('district_title' => 'Banda','state_id' => '33'),
            array('district_title' => 'Barabanki','state_id' => '33'),
            array('district_title' => 'Bareilly','state_id' => '33'),
            array('district_title' => 'Basti','state_id' => '33'),
            array('district_title' => 'Bijnor','state_id' => '33'),
            array('district_title' => 'Budaun','state_id' => '33'),
            array('district_title' => 'Bulandshahr','state_id' => '33'),
            array('district_title' => 'Chandauli','state_id' => '33'),
            array('district_title' => 'Chitrakoot','state_id' => '33'),
            array('district_title' => 'Deoria','state_id' => '33'),
            array('district_title' => 'Etah','state_id' => '33'),
            array('district_title' => 'Etawah','state_id' => '33'),
            array('district_title' => 'Faizabad','state_id' => '33'),
            array('district_title' => 'Farrukhabad','state_id' => '33'),
            array('district_title' => 'Fatehpur','state_id' => '33'),
            array('district_title' => 'Firozabad','state_id' => '33'),
            array('district_title' => 'Gautam Buddha Nagar','state_id' => '33'),
            array('district_title' => 'Ghaziabad','state_id' => '33'),
            array('district_title' => 'Ghazipur','state_id' => '33'),
            array('district_title' => 'Gonda','state_id' => '33'),
            array('district_title' => 'Gorakhpur','state_id' => '33'),
            array('district_title' => 'Hamirpur','state_id' => '33'),
            array('district_title' => 'Hardoi','state_id' => '33'),
            array('district_title' => 'Hathras','state_id' => '33'),
            array('district_title' => 'Jalaun','state_id' => '33'),
            array('district_title' => 'Jaunpur','state_id' => '33'),
            array('district_title' => 'Jhansi','state_id' => '33'),
            array('district_title' => 'Jyotiba Phule Nagar','state_id' => '33'),
            array('district_title' => 'Kannauj','state_id' => '33'),
            array('district_title' => 'Kanpur Dehat','state_id' => '33'),
            array('district_title' => 'Kanpur Nagar','state_id' => '33'),
            array('district_title' => 'Kanshiram Nagar','state_id' => '33'),
            array('district_title' => 'Kaushambi','state_id' => '33'),
            array('district_title' => 'Kheri','state_id' => '33'),
            array('district_title' => 'Kushinagar','state_id' => '33'),
            array('district_title' => 'Lalitpur','state_id' => '33'),
            array('district_title' => 'Lucknow','state_id' => '33'),
            array('district_title' => 'Maharajganj','state_id' => '33'),
            array('district_title' => 'Mahoba','state_id' => '33'),
            array('district_title' => 'Mainpuri','state_id' => '33'),
            array('district_title' => 'Mathura','state_id' => '33'),
            array('district_title' => 'Mau','state_id' => '33'),
            array('district_title' => 'Meerut','state_id' => '33'),
            array('district_title' => 'Mirzapur','state_id' => '33'),
            array('district_title' => 'Moradabad','state_id' => '33'),
            array('district_title' => 'Muzaffarnagar','state_id' => '33'),
            array('district_title' => 'Pilibhit','state_id' => '33'),
            array('district_title' => 'Pratapgarh','state_id' => '33'),
            array('district_title' => 'Rae Bareli','state_id' => '33'),
            array('district_title' => 'Rampur','state_id' => '33'),
            array('district_title' => 'Saharanpur','state_id' => '33'),
            array('district_title' => 'Sant Kabir Nagar','state_id' => '33'),
            array('district_title' => 'Sant Ravidas Nagar (Bhadohi)','state_id' => '33'),
            array('district_title' => 'Shahjahanpur','state_id' => '33'),
            array('district_title' => 'Shrawasti','state_id' => '33'),
            array('district_title' => 'Siddharthnagar','state_id' => '33'),
            array('district_title' => 'Sitapur','state_id' => '33'),
            array('district_title' => 'Sonbhadra','state_id' => '33'),
            array('district_title' => 'Sultanpur','state_id' => '33'),
            array('district_title' => 'Unnao','state_id' => '33'),
            array('district_title' => 'Varanasi','state_id' => '33'),
            array('district_title' => 'Araria','state_id' => '5'),
            array('district_title' => 'Arwal','state_id' => '5'),
            array('district_title' => 'Aurangabad (Bihar)','state_id' => '5'),
            array('district_title' => 'Banka','state_id' => '5'),
            array('district_title' => 'Begusarai','state_id' => '5'),
            array('district_title' => 'Bhagalpur','state_id' => '5'),
            array('district_title' => 'Bhojpur','state_id' => '5'),
            array('district_title' => 'Buxar','state_id' => '5'),
            array('district_title' => 'Darbhanga','state_id' => '5'),
            array('district_title' => 'East Champaran','state_id' => '5'),
            array('district_title' => 'Gaya','state_id' => '5'),
            array('district_title' => 'Gopalganj','state_id' => '5'),
            array('district_title' => 'Jamui','state_id' => '5'),
            array('district_title' => 'Jehanabad','state_id' => '5'),
            array('district_title' => 'Kaimur (Bhabua)','state_id' => '5'),
            array('district_title' => 'Katihar','state_id' => '5'),
            array('district_title' => 'Khagaria','state_id' => '5'),
            array('district_title' => 'Kishanganj','state_id' => '5'),
            array('district_title' => 'Lakhisarai','state_id' => '5'),
            array('district_title' => 'Madhepura','state_id' => '5'),
            array('district_title' => 'Madhubani','state_id' => '5'),
            array('district_title' => 'Munger','state_id' => '5'),
            array('district_title' => 'Muzaffarpur','state_id' => '5'),
            array('district_title' => 'Nalanda','state_id' => '5'),
            array('district_title' => 'Nawada','state_id' => '5'),
            array('district_title' => 'Patna','state_id' => '5'),
            array('district_title' => 'Purnia','state_id' => '5'),
            array('district_title' => 'Rohtas','state_id' => '5'),
            array('district_title' => 'Saharsa','state_id' => '5'),
            array('district_title' => 'Samastipur','state_id' => '5'),
            array('district_title' => 'Saran','state_id' => '5'),
            array('district_title' => 'Sheikhpura','state_id' => '5'),
            array('district_title' => 'Sheohar','state_id' => '5'),
            array('district_title' => 'Sitamarhi','state_id' => '5'),
            array('district_title' => 'Siwan','state_id' => '5'),
            array('district_title' => 'Supaul','state_id' => '5'),
            array('district_title' => 'Vaishali','state_id' => '5'),
            array('district_title' => 'West Champaran','state_id' => '5'),
            array('district_title' => 'East Sikkim','state_id' => '30'),
            array('district_title' => 'North Sikkim','state_id' => '30'),
            array('district_title' => 'South Sikkim','state_id' => '30'),
            array('district_title' => 'West Sikkim','state_id' => '30'),
            array('district_title' => 'Anjaw','state_id' => '3'),
            array('district_title' => 'Changlang','state_id' => '3'),
            array('district_title' => 'Dibang Valley','state_id' => '3'),
            array('district_title' => 'East Kameng','state_id' => '3'),
            array('district_title' => 'East Siang','state_id' => '3'),
            array('district_title' => 'Kurung Kumey','state_id' => '3'),
            array('district_title' => 'Lohit','state_id' => '3'),
            array('district_title' => 'Lower Dibang Valley','state_id' => '3'),
            array('district_title' => 'Lower Subansiri','state_id' => '3'),
            array('district_title' => 'Papum Pare','state_id' => '3'),
            array('district_title' => 'Tawang','state_id' => '3'),
            array('district_title' => 'Tirap','state_id' => '3'),
            array('district_title' => 'Upper Siang','state_id' => '3'),
            array('district_title' => 'Upper Subansiri','state_id' => '3'),
            array('district_title' => 'West Kameng','state_id' => '3'),
            array('district_title' => 'West Siang','state_id' => '3'),
            array('district_title' => 'Dimapur','state_id' => '25'),
            array('district_title' => 'Kiphire','state_id' => '25'),
            array('district_title' => 'Kohima','state_id' => '25'),
            array('district_title' => 'Longleng','state_id' => '25'),
            array('district_title' => 'Mokokchung','state_id' => '25'),
            array('district_title' => 'Mon','state_id' => '25'),
            array('district_title' => 'Peren','state_id' => '25'),
            array('district_title' => 'Phek','state_id' => '25'),
            array('district_title' => 'Tuensang','state_id' => '25'),
            array('district_title' => 'Wokha','state_id' => '25'),
            array('district_title' => 'Zunheboto','state_id' => '25'),
            array('district_title' => 'Bishnupur','state_id' => '22'),
            array('district_title' => 'Chandel','state_id' => '22'),
            array('district_title' => 'Churachandpur','state_id' => '22'),
            array('district_title' => 'Imphal East','state_id' => '22'),
            array('district_title' => 'Imphal West','state_id' => '22'),
            array('district_title' => 'Senapati','state_id' => '22'),
            array('district_title' => 'Tamenglong','state_id' => '22'),
            array('district_title' => 'Thoubal','state_id' => '22'),
            array('district_title' => 'Ukhrul','state_id' => '22'),
            array('district_title' => 'Aizawl','state_id' => '24'),
            array('district_title' => 'Champhai','state_id' => '24'),
            array('district_title' => 'Kolasib','state_id' => '24'),
            array('district_title' => 'Lawngtlai','state_id' => '24'),
            array('district_title' => 'Lunglei','state_id' => '24'),
            array('district_title' => 'Mamit','state_id' => '24'),
            array('district_title' => 'Saiha','state_id' => '24'),
            array('district_title' => 'Serchhip','state_id' => '24'),
            array('district_title' => 'Dhalai','state_id' => '32'),
            array('district_title' => 'North Tripura','state_id' => '32'),
            array('district_title' => 'South Tripura','state_id' => '32'),
            array('district_title' => 'West Tripura','state_id' => '32'),
            array('district_title' => 'East Garo Hills','state_id' => '23'),
            array('district_title' => 'East Khasi Hills','state_id' => '23'),
            array('district_title' => 'Jaintia Hills','state_id' => '23'),
            array('district_title' => 'Ri Bhoi','state_id' => '23'),
            array('district_title' => 'South Garo Hills','state_id' => '23'),
            array('district_title' => 'West Garo Hills','state_id' => '23'),
            array('district_title' => 'West Khasi Hills','state_id' => '23'),
            array('district_title' => 'Baksa','state_id' => '4'),
            array('district_title' => 'Barpeta','state_id' => '4'),
            array('district_title' => 'Bongaigaon','state_id' => '4'),
            array('district_title' => 'Cachar','state_id' => '4'),
            array('district_title' => 'Chirang','state_id' => '4'),
            array('district_title' => 'Darrang','state_id' => '4'),
            array('district_title' => 'Dhemaji','state_id' => '4'),
            array('district_title' => 'Dhubri','state_id' => '4'),
            array('district_title' => 'Dibrugarh','state_id' => '4'),
            array('district_title' => 'Dima Hasao (North Cachar Hills)','state_id' => '4'),
            array('district_title' => 'Goalpara','state_id' => '4'),
            array('district_title' => 'Golaghat','state_id' => '4'),
            array('district_title' => 'Hailakandi','state_id' => '4'),
            array('district_title' => 'Jorhat','state_id' => '4'),
            array('district_title' => 'Kamrup','state_id' => '4'),
            array('district_title' => 'Kamrup Metropolitan','state_id' => '4'),
            array('district_title' => 'Karbi Anglong','state_id' => '4'),
            array('district_title' => 'Karimganj','state_id' => '4'),
            array('district_title' => 'Kokrajhar','state_id' => '4'),
            array('district_title' => 'Lakhimpur','state_id' => '4'),
            array('district_title' => 'Morigaon','state_id' => '4'),
            array('district_title' => 'Nagaon','state_id' => '4'),
            array('district_title' => 'Nalbari','state_id' => '4'),
            array('district_title' => 'Sivasagar','state_id' => '4'),
            array('district_title' => 'Sonitpur','state_id' => '4'),
            array('district_title' => 'Tinsukia','state_id' => '4'),
            array('district_title' => 'Udalguri','state_id' => '4'),
            array('district_title' => 'Bankura','state_id' => '35'),
            array('district_title' => 'Bardhaman','state_id' => '35'),
            array('district_title' => 'Birbhum','state_id' => '35'),
            array('district_title' => 'Cooch Behar','state_id' => '35'),
            array('district_title' => 'Dakshin Dinajpur (South Dinajpur)','state_id' => '35'),
            array('district_title' => 'Darjiling','state_id' => '35'),
            array('district_title' => 'Hooghly','state_id' => '35'),
            array('district_title' => 'Howrah','state_id' => '35'),
            array('district_title' => 'Jalpaiguri','state_id' => '35'),
            array('district_title' => 'Kolkata','state_id' => '35'),
            array('district_title' => 'Maldah','state_id' => '35'),
            array('district_title' => 'Murshidabad','state_id' => '35'),
            array('district_title' => 'Nadia','state_id' => '35'),
            array('district_title' => 'North 24 Parganas','state_id' => '35'),
            array('district_title' => 'Paschim Medinipur (West Midnapore)','state_id' => '35'),
            array('district_title' => 'Purba Medinipur (East Midnapore)','state_id' => '35'),
            array('district_title' => 'Puruliya','state_id' => '35'),
            array('district_title' => 'South 24 Parganas','state_id' => '35'),
            array('district_title' => 'Uttar Dinajpur (North Dinajpur)','state_id' => '35'),
            array('district_title' => 'Bokaro','state_id' => '16'),
            array('district_title' => 'Chatra','state_id' => '16'),
            array('district_title' => 'Deoghar','state_id' => '16'),
            array('district_title' => 'Dhanbad','state_id' => '16'),
            array('district_title' => 'Dumka','state_id' => '16'),
            array('district_title' => 'East Singhbhum','state_id' => '16'),
            array('district_title' => 'Garhwa','state_id' => '16'),
            array('district_title' => 'Giridih','state_id' => '16'),
            array('district_title' => 'Godda','state_id' => '16'),
            array('district_title' => 'Gumla','state_id' => '16'),
            array('district_title' => 'Hazaribagh','state_id' => '16'),
            array('district_title' => 'Jamtara','state_id' => '16'),
            array('district_title' => 'Khunti','state_id' => '16'),
            array('district_title' => 'Koderma','state_id' => '16'),
            array('district_title' => 'Latehar','state_id' => '16'),
            array('district_title' => 'Lohardaga','state_id' => '16'),
            array('district_title' => 'Pakur','state_id' => '16'),
            array('district_title' => 'Palamu','state_id' => '16'),
            array('district_title' => 'Ramgarh','state_id' => '16'),
            array('district_title' => 'Ranchi','state_id' => '16'),
            array('district_title' => 'Sahibganj','state_id' => '16'),
            array('district_title' => 'Seraikela-Kharsawan','state_id' => '16'),
            array('district_title' => 'Simdega','state_id' => '16'),
            array('district_title' => 'West Singhbhum','state_id' => '16'),
            array('district_title' => 'Angul','state_id' => '26'),
            array('district_title' => 'Balangir','state_id' => '26'),
            array('district_title' => 'Baleswar','state_id' => '26'),
            array('district_title' => 'Bargarh','state_id' => '26'),
            array('district_title' => 'Bhadrak','state_id' => '26'),
            array('district_title' => 'Boudh','state_id' => '26'),
            array('district_title' => 'Cuttack','state_id' => '26'),
            array('district_title' => 'Debagarh','state_id' => '26'),
            array('district_title' => 'Dhenkanal','state_id' => '26'),
            array('district_title' => 'Gajapati','state_id' => '26'),
            array('district_title' => 'Ganjam','state_id' => '26'),
            array('district_title' => 'Jagatsinghapur','state_id' => '26'),
            array('district_title' => 'Jajapur','state_id' => '26'),
            array('district_title' => 'Jharsuguda','state_id' => '26'),
            array('district_title' => 'Kalahandi','state_id' => '26'),
            array('district_title' => 'Kandhamal','state_id' => '26'),
            array('district_title' => 'Kendrapara','state_id' => '26'),
            array('district_title' => 'Kendujhar','state_id' => '26'),
            array('district_title' => 'Khordha','state_id' => '26'),
            array('district_title' => 'Koraput','state_id' => '26'),
            array('district_title' => 'Malkangiri','state_id' => '26'),
            array('district_title' => 'Mayurbhanj','state_id' => '26'),
            array('district_title' => 'Nabarangapur','state_id' => '26'),
            array('district_title' => 'Nayagarh','state_id' => '26'),
            array('district_title' => 'Nuapada','state_id' => '26'),
            array('district_title' => 'Puri','state_id' => '26'),
            array('district_title' => 'Rayagada','state_id' => '26'),
            array('district_title' => 'Sambalpur','state_id' => '26'),
            array('district_title' => 'Subarnapur (Sonapur)','state_id' => '26'),
            array('district_title' => 'Sundergarh','state_id' => '26'),
            array('district_title' => 'Bastar','state_id' => '7'),
            array('district_title' => 'Bijapur (Chhattisgarh)','state_id' => '7'),
            array('district_title' => 'Bilaspur (Chhattisgarh)','state_id' => '7'),
            array('district_title' => 'Dakshin Bastar Dantewada','state_id' => '7'),
            array('district_title' => 'Dhamtari','state_id' => '7'),
            array('district_title' => 'Durg','state_id' => '7'),
            array('district_title' => 'Janjgir-Champa','state_id' => '7'),
            array('district_title' => 'Jashpur','state_id' => '7'),
            array('district_title' => 'Kabirdham (Kawardha)','state_id' => '7'),
            array('district_title' => 'Korba','state_id' => '7'),
            array('district_title' => 'Koriya','state_id' => '7'),
            array('district_title' => 'Mahasamund','state_id' => '7'),
            array('district_title' => 'Narayanpur','state_id' => '7'),
            array('district_title' => 'Raigarh (Chhattisgarh)','state_id' => '7'),
            array('district_title' => 'Raipur','state_id' => '7'),
            array('district_title' => 'Rajnandgaon','state_id' => '7'),
            array('district_title' => 'Surguja','state_id' => '7'),
            array('district_title' => 'Uttar Bastar Kanker','state_id' => '7'),
            array('district_title' => 'Alirajpur','state_id' => '20'),
            array('district_title' => 'Anuppur','state_id' => '20'),
            array('district_title' => 'Ashok Nagar','state_id' => '20'),
            array('district_title' => 'Balaghat','state_id' => '20'),
            array('district_title' => 'Barwani','state_id' => '20'),
            array('district_title' => 'Betul','state_id' => '20'),
            array('district_title' => 'Bhind','state_id' => '20'),
            array('district_title' => 'Bhopal','state_id' => '20'),
            array('district_title' => 'Burhanpur','state_id' => '20'),
            array('district_title' => 'Chhatarpur','state_id' => '20'),
            array('district_title' => 'Chhindwara','state_id' => '20'),
            array('district_title' => 'Damoh','state_id' => '20'),
            array('district_title' => 'Datia','state_id' => '20'),
            array('district_title' => 'Dewas','state_id' => '20'),
            array('district_title' => 'Dhar','state_id' => '20'),
            array('district_title' => 'Dindori','state_id' => '20'),
            array('district_title' => 'Guna','state_id' => '20'),
            array('district_title' => 'Gwalior','state_id' => '20'),
            array('district_title' => 'Harda','state_id' => '20'),
            array('district_title' => 'Hoshangabad','state_id' => '20'),
            array('district_title' => 'Indore','state_id' => '20'),
            array('district_title' => 'Jabalpur','state_id' => '20'),
            array('district_title' => 'Jhabua','state_id' => '20'),
            array('district_title' => 'Katni','state_id' => '20'),
            array('district_title' => 'Khandwa (East Nimar)','state_id' => '20'),
            array('district_title' => 'Khargone (West Nimar)','state_id' => '20'),
            array('district_title' => 'Mandla','state_id' => '20'),
            array('district_title' => 'Mandsaur','state_id' => '20'),
            array('district_title' => 'Morena','state_id' => '20'),
            array('district_title' => 'Narsinghpur','state_id' => '20'),
            array('district_title' => 'Neemuch','state_id' => '20'),
            array('district_title' => 'Panna','state_id' => '20'),
            array('district_title' => 'Raisen','state_id' => '20'),
            array('district_title' => 'Rajgarh','state_id' => '20'),
            array('district_title' => 'Ratlam','state_id' => '20'),
            array('district_title' => 'Rewa','state_id' => '20'),
            array('district_title' => 'Sagar','state_id' => '20'),
            array('district_title' => 'Satna','state_id' => '20'),
            array('district_title' => 'Sehore','state_id' => '20'),
            array('district_title' => 'Seoni','state_id' => '20'),
            array('district_title' => 'Shahdol','state_id' => '20'),
            array('district_title' => 'Shajapur','state_id' => '20'),
            array('district_title' => 'Sheopur','state_id' => '20'),
            array('district_title' => 'Shivpuri','state_id' => '20'),
            array('district_title' => 'Sidhi','state_id' => '20'),
            array('district_title' => 'Singrauli','state_id' => '20'),
            array('district_title' => 'Tikamgarh','state_id' => '20'),
            array('district_title' => 'Ujjain','state_id' => '20'),
            array('district_title' => 'Umaria','state_id' => '20'),
            array('district_title' => 'Vidisha','state_id' => '20'),
            array('district_title' => 'Ahmedabad','state_id' => '12'),
            array('district_title' => 'Amreli','state_id' => '12'),
            array('district_title' => 'Anand','state_id' => '12'),
            array('district_title' => 'Banaskantha','state_id' => '12'),
            array('district_title' => 'Bharuch','state_id' => '12'),
            array('district_title' => 'Bhavnagar','state_id' => '12'),
            array('district_title' => 'Dahod','state_id' => '12'),
            array('district_title' => 'Gandhi Nagar','state_id' => '12'),
            array('district_title' => 'Jamnagar','state_id' => '12'),
            array('district_title' => 'Junagadh','state_id' => '12'),
            array('district_title' => 'Kachchh','state_id' => '12'),
            array('district_title' => 'Kheda','state_id' => '12'),
            array('district_title' => 'Mahesana','state_id' => '12'),
            array('district_title' => 'Narmada','state_id' => '12'),
            array('district_title' => 'Navsari','state_id' => '12'),
            array('district_title' => 'Panch Mahals','state_id' => '12'),
            array('district_title' => 'Patan','state_id' => '12'),
            array('district_title' => 'Porbandar','state_id' => '12'),
            array('district_title' => 'Rajkot','state_id' => '12'),
            array('district_title' => 'Sabarkantha','state_id' => '12'),
            array('district_title' => 'Surat','state_id' => '12'),
            array('district_title' => 'Surendra Nagar','state_id' => '12'),
            array('district_title' => 'Tapi','state_id' => '12'),
            array('district_title' => 'The Dangs','state_id' => '12'),
            array('district_title' => 'Vadodara','state_id' => '12'),
            array('district_title' => 'Valsad','state_id' => '12'),
            array('district_title' => 'Daman','state_id' => '9'),
            array('district_title' => 'Diu','state_id' => '9'),
            array('district_title' => 'Dadra & Nagar Haveli','state_id' => '8'),
            array('district_title' => 'Ahmed Nagar','state_id' => '21'),
            array('district_title' => 'Akola','state_id' => '21'),
            array('district_title' => 'Amravati','state_id' => '21'),
            array('district_title' => 'Aurangabad','state_id' => '21'),
            array('district_title' => 'Beed','state_id' => '21'),
            array('district_title' => 'Bhandara','state_id' => '21'),
            array('district_title' => 'Buldhana','state_id' => '21'),
            array('district_title' => 'Chandrapur','state_id' => '21'),
            array('district_title' => 'Dhule','state_id' => '21'),
            array('district_title' => 'Gadchiroli','state_id' => '21'),
            array('district_title' => 'Gondia','state_id' => '21'),
            array('district_title' => 'Hingoli','state_id' => '21'),
            array('district_title' => 'Jalgaon','state_id' => '21'),
            array('district_title' => 'Jalna','state_id' => '21'),
            array('district_title' => 'Kolhapur','state_id' => '21'),
            array('district_title' => 'Latur','state_id' => '21'),
            array('district_title' => 'Mumbai','state_id' => '21'),
            array('district_title' => 'Mumbai Suburban','state_id' => '21'),
            array('district_title' => 'Nagpur','state_id' => '21'),
            array('district_title' => 'Nanded','state_id' => '21'),
            array('district_title' => 'Nandurbar','state_id' => '21'),
            array('district_title' => 'Nashik','state_id' => '21'),
            array('district_title' => 'Osmanabad','state_id' => '21'),
            array('district_title' => 'Parbhani','state_id' => '21'),
            array('district_title' => 'Pune','state_id' => '21'),
            array('district_title' => 'Raigarh (Maharashtra)','state_id' => '21'),
            array('district_title' => 'Ratnagiri','state_id' => '21'),
            array('district_title' => 'Sangli','state_id' => '21'),
            array('district_title' => 'Satara','state_id' => '21'),
            array('district_title' => 'Sindhudurg','state_id' => '21'),
            array('district_title' => 'Solapur','state_id' => '21'),
            array('district_title' => 'Thane','state_id' => '21'),
            array('district_title' => 'Wardha','state_id' => '21'),
            array('district_title' => 'Washim','state_id' => '21'),
            array('district_title' => 'Yavatmal','state_id' => '21'),
            array('district_title' => 'Adilabad','state_id' => '2'),
            array('district_title' => 'Anantapur','state_id' => '2'),
            array('district_title' => 'Chittoor','state_id' => '2'),
            array('district_title' => 'East Godavari','state_id' => '2'),
            array('district_title' => 'Guntur','state_id' => '2'),
            array('district_title' => 'Hyderabad','state_id' => '2'),
            array('district_title' => 'Kadapa (Cuddapah)','state_id' => '2'),
            array('district_title' => 'Karim Nagar','state_id' => '2'),
            array('district_title' => 'Khammam','state_id' => '2'),
            array('district_title' => 'Krishna','state_id' => '2'),
            array('district_title' => 'Kurnool','state_id' => '2'),
            array('district_title' => 'Mahbubnagar','state_id' => '2'),
            array('district_title' => 'Medak','state_id' => '2'),
            array('district_title' => 'Nalgonda','state_id' => '2'),
            array('district_title' => 'Nellore','state_id' => '2'),
            array('district_title' => 'Nizamabad','state_id' => '2'),
            array('district_title' => 'Prakasam','state_id' => '2'),
            array('district_title' => 'Rangareddy','state_id' => '2'),
            array('district_title' => 'Srikakulam','state_id' => '2'),
            array('district_title' => 'Visakhapatnam','state_id' => '2'),
            array('district_title' => 'Vizianagaram','state_id' => '2'),
            array('district_title' => 'Warangal','state_id' => '2'),
            array('district_title' => 'West Godavari','state_id' => '2'),
            array('district_title' => 'Bagalkot','state_id' => '17'),
            array('district_title' => 'Bangalore','state_id' => '17'),
            array('district_title' => 'Bangalore Rural','state_id' => '17'),
            array('district_title' => 'Belgaum','state_id' => '17'),
            array('district_title' => 'Bellary','state_id' => '17'),
            array('district_title' => 'Bidar','state_id' => '17'),
            array('district_title' => 'Bijapur (Karnataka)','state_id' => '17'),
            array('district_title' => 'Chamrajnagar','state_id' => '17'),
            array('district_title' => 'Chickmagalur','state_id' => '17'),
            array('district_title' => 'Chikkaballapur','state_id' => '17'),
            array('district_title' => 'Chitradurga','state_id' => '17'),
            array('district_title' => 'Dakshina Kannada','state_id' => '17'),
            array('district_title' => 'Davanagere','state_id' => '17'),
            array('district_title' => 'Dharwad','state_id' => '17'),
            array('district_title' => 'Gadag','state_id' => '17'),
            array('district_title' => 'Gulbarga','state_id' => '17'),
            array('district_title' => 'Hassan','state_id' => '17'),
            array('district_title' => 'Haveri','state_id' => '17'),
            array('district_title' => 'Kodagu','state_id' => '17'),
            array('district_title' => 'Kolar','state_id' => '17'),
            array('district_title' => 'Koppal','state_id' => '17'),
            array('district_title' => 'Mandya','state_id' => '17'),
            array('district_title' => 'Mysore','state_id' => '17'),
            array('district_title' => 'Raichur','state_id' => '17'),
            array('district_title' => 'Ramanagara','state_id' => '17'),
            array('district_title' => 'Shimoga','state_id' => '17'),
            array('district_title' => 'Tumkur','state_id' => '17'),
            array('district_title' => 'Udupi','state_id' => '17'),
            array('district_title' => 'Uttara Kannada','state_id' => '17'),
            array('district_title' => 'Yadgir','state_id' => '17'),
            array('district_title' => 'North Goa','state_id' => '11'),
            array('district_title' => 'South Goa','state_id' => '11'),
            array('district_title' => 'Lakshadweep','state_id' => '19'),
            array('district_title' => 'Alappuzha','state_id' => '18'),
            array('district_title' => 'Ernakulam','state_id' => '18'),
            array('district_title' => 'Idukki','state_id' => '18'),
            array('district_title' => 'Kannur','state_id' => '18'),
            array('district_title' => 'Kasaragod','state_id' => '18'),
            array('district_title' => 'Kollam','state_id' => '18'),
            array('district_title' => 'Kottayam','state_id' => '18'),
            array('district_title' => 'Kozhikode','state_id' => '18'),
            array('district_title' => 'Malappuram','state_id' => '18'),
            array('district_title' => 'Palakkad','state_id' => '18'),
            array('district_title' => 'Pathanamthitta','state_id' => '18'),
            array('district_title' => 'Thiruvananthapuram','state_id' => '18'),
            array('district_title' => 'Thrissur','state_id' => '18'),
            array('district_title' => 'Wayanad','state_id' => '18'),
            array('district_title' => 'Ariyalur','state_id' => '31'),
            array('district_title' => 'Chennai','state_id' => '31'),
            array('district_title' => 'Coimbatore','state_id' => '31'),
            array('district_title' => 'Cuddalore','state_id' => '31'),
            array('district_title' => 'Dharmapuri','state_id' => '31'),
            array('district_title' => 'Dindigul','state_id' => '31'),
            array('district_title' => 'Erode','state_id' => '31'),
            array('district_title' => 'Kanchipuram','state_id' => '31'),
            array('district_title' => 'Kanyakumari','state_id' => '31'),
            array('district_title' => 'Karur','state_id' => '31'),
            array('district_title' => 'Krishnagiri','state_id' => '31'),
            array('district_title' => 'Madurai','state_id' => '31'),
            array('district_title' => 'Nagapattinam','state_id' => '31'),
            array('district_title' => 'Namakkal','state_id' => '31'),
            array('district_title' => 'Nilgiris','state_id' => '31'),
            array('district_title' => 'Perambalur','state_id' => '31'),
            array('district_title' => 'Pudukkottai','state_id' => '31'),
            array('district_title' => 'Ramanathapuram','state_id' => '31'),
            array('district_title' => 'Salem','state_id' => '31'),
            array('district_title' => 'Sivaganga','state_id' => '31'),
            array('district_title' => 'Thanjavur','state_id' => '31'),
            array('district_title' => 'Theni','state_id' => '31'),
            array('district_title' => 'Thoothukudi (Tuticorin)','state_id' => '31'),
            array('district_title' => 'Tiruchirappalli','state_id' => '31'),
            array('district_title' => 'Tirunelveli','state_id' => '31'),
            array('district_title' => 'Tiruppur','state_id' => '31'),
            array('district_title' => 'Tiruvallur','state_id' => '31'),
            array('district_title' => 'Tiruvannamalai','state_id' => '31'),
            array('district_title' => 'Tiruvarur','state_id' => '31'),
            array('district_title' => 'Vellore','state_id' => '31'),
            array('district_title' => 'Viluppuram','state_id' => '31'),
            array('district_title' => 'Virudhunagar','state_id' => '31'),
            array('district_title' => 'Karaikal','state_id' => '27'),
            array('district_title' => 'Mahe','state_id' => '27'),
            array('district_title' => 'Puducherry (Pondicherry)','state_id' => '27'),
            array('district_title' => 'Yanam','state_id' => '27'),
            array('district_title' => 'Nicobar','state_id' => '1'),
            array('district_title' => 'North And Middle Andaman','state_id' => '1'),
            array('district_title' => 'South Andaman','state_id' => '1')
          );

          foreach ($district as $item) {
                DB::table('district')->insert(['district_name' => $item['district_title'],'state_id'=>$item['state_id']], $item);
                }
    }
}
